laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('resultados-filtro/{area}/{aplicacao}/{servico}', 'FiltroController@index')->name('filtro');
    Route::get('filtro/{area}/{aplicacao}/{servico}', 'FiltroController@filtroGeral')->name('filtroGeral');
    Route::get('empresa/{submenu}', 'EmpresaController@index')->name('empresa');
    Route::get('empresa/list/{submenu}', 'EmpresaController@getDadosEmpresa')->name('getDadosEmpresa');
    Route::get('areas-de-negocio/{area}', 'AreasDeNegocioController@index')->name('areas-de-negocio');
    Route::get('areas-de-negocio/list/{area}', 'AreasDeNegocioController@getDadosAreasDeNegocio')->name('getDadosAreasDeNegocio');
    Route::get('aplicacoes/{aplicacao}', 'AplicacoesController@index')->name('aplicacoes');
    Route::get('aplicacoes/list/{aplicacao}', 'AplicacoesController@getDadosAplicacoes')->name('getDadosAplicacoes');
    Route::get('servicos', 'ServicosController@index')->name('servicos');
    Route::get('servicos/{servico}', 'ServicosController@show')->name('servicos.show');
    Route::get('servicos/grupo/{grupo}', 'ServicosController@showServicosGrupo')->name('showServicosGrupo');
    Route::get('servicos/list/{servico}', 'ServicosController@getDadosServicos')->name('getDadosServicos');
    Route::get('galeria-de-imagens', 'GaleriaDeImagensController@index')->name('galeria-de-imagens.index');
    Route::get('galeria-de-imagens/{obra}', 'GaleriaDeImagensController@show')->name('galeria-de-imagens.show');
    Route::get('galeria-de-imagens/filtro/{area}/{aplicacao}/{servico}', 'GaleriaDeImagensController@filtroGaleria')->name('filtroGaleria');
    Route::get('artigos-tecnicos', 'ArtigosTecnicosController@index')->name('artigos-tecnicos');
    Route::get('artigos-tecnicos/{artigo}', 'ArtigosTecnicosController@openPdf')->name('artigos-tecnicos.pdf');
    Route::get('clientes', 'ClientesController@index')->name('clientes');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('busca', 'BuscaController@post')->name('busca');
    Route::get('termos-de-uso', 'TermosDeUsoController@index')->name('termos-de-uso');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
        Route::resource('capas-menus', 'CapasMenusController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('banners-header', 'BannersHeaderController');
        Route::resource('slides-home', 'SlidesHomeController');
        Route::resource('obras-destaque', 'ObrasDestaqueController', ['only' => ['index', 'create', 'store', 'destroy']]);
        Route::resource('empresa-historia', 'EmpresaHistoriaController', ['only' => ['index', 'update']]);
        Route::resource('empresa-nossa-otica', 'EmpresaNossaOticaController', ['only' => ['index', 'update']]);
        Route::resource('empresa-corpo-tecnico', 'EmpresaCorpoTecnicoController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('empresa-corpo-tecnico.equipe', 'EmpresaCorpoTecnicoEquipeController');
        Route::resource('areas-de-negocio', 'AreasDeNegocioController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('servicos-pagina', 'ServicosPaginaController', ['only' => ['index', 'update']]);
        Route::resource('servicos-grupos', 'ServicosGruposController');
        Route::resource('servicos', 'ServicosController', ['except' => 'show']);
        Route::get('servicos/{servico}/imagens/clear', [
            'as'   => 'painel.servicos.imagens.clear',
            'uses' => 'ServicosImagensController@clear'
        ]);
        Route::resource('servicos.imagens', 'ServicosImagensController', ['parameters' => ['imagens' => 'servicos_imagens']]);
        Route::resource('aplicacoes', 'AplicacoesController');
        Route::resource('aplicacoes.areas', 'AplicacoesAreasController');
        Route::resource('aplicacoes.areas.servicos', 'AplicacoesAreasServicosController', ['only' => ['index', 'create', 'store', 'destroy']]);
        Route::resource('galeria-de-imagens', 'ObrasController');
        Route::resource('galeria-de-imagens.areas', 'ObrasAreasController', ['only' => ['index', 'create', 'store', 'destroy']]);
        Route::resource('galeria-de-imagens.servicos', 'ObrasServicosController', ['only' => ['index', 'create', 'store']]);
        Route::delete('galeria-de-imagens/{obra}/servicos/{servico}', 'ObrasServicosController@destroy')->name('galeria.servicos.destroy');
        Route::resource('galeria-de-imagens.imagens', 'ObrasImagensController');
        Route::resource('artigos-tecnicos', 'ArtigosTecnicosController');
        Route::resource('clientes', 'ClientesController');
        Route::get('contato/recebidos/{recebidos}/pdf', 'ContatosRecebidosController@openPdf')->name('painel.contato.arquivos.pdf');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');
        Route::resource('termos-de-uso', 'TermosDeUsoController', ['only' => ['index', 'update']]);
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');

        // Limpar caches
        Route::get('clear-cache', function () {
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('config:cache');

            return 'DONE';
        });
    });

    // Auth - PAINEL
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Http/Controllers/AplicacoesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Aplicacao;
use App\Models\AreaDeNegocio;
use App\Models\Servico;

class AplicacoesController extends Controller
{
    public function index($aplicacao)
    {
        $aplicacoes = Aplicacao::orderBy('titulo', 'ASC')->get();

        $aplicacaoInicial = $aplicacoes->where('slug', $aplicacao)->first();

        $aplicacoesAreas = AreaDeNegocio::join('aplicacoes_areas', 'aplicacoes_areas.area_id', '=', 'areas_de_negocio.id')
            ->join('aplicacoes', 'aplicacoes.id', '=', 'aplicacoes_areas.aplicacao_id')
            ->select('areas_de_negocio.id as area_id', 'areas_de_negocio.slug as area_slug', 'areas_de_negocio.titulo as area_titulo', 'aplicacoes_areas.texto_area as texto_area')
            ->where('aplicacoes.slug', $aplicacao)
            ->distinct()->orderBy('areas_de_negocio.id', 'ASC')->get();

        $aplicacoesServicos = Servico::join('aplicacoes_areas_servicos', 'aplicacoes_areas_servicos.servico_id', '=', 'servicos.id')
            ->join('aplicacoes_areas', 'aplicacoes_areas.id', '=', 'aplicacoes_areas_servicos.aplicacao_area_id')
            ->join('aplicacoes', 'aplicacoes.id', '=', 'aplicacoes_areas.aplicacao_id')
            ->join('areas_de_negocio', 'areas_de_negocio.id', '=', 'aplicacoes_areas.area_id')
            ->select('aplicacoes.id as aplicacao_id', 'aplicacoes.slug as aplicacao_slug', 'aplicacoes.titulo as aplicacao_titulo', 'areas_de_negocio.id as area_id', 'areas_de_negocio.slug as area_slug', 'areas_de_negocio.titulo as area_titulo', 'servicos.id as servico_id', 'servicos.slug as servico_slug', 'servicos.titulo as servico_titulo', 'servicos.grupo_id as grupo_id')
            ->where('aplicacoes.id', $aplicacaoInicial->id)
            ->orderBy('servicos.titulo', 'ASC')->get();

        // dd($aplicacoesServicos);

        return view('frontend.aplicacoes', compact('aplicacoes', 'aplicacaoInicial', 'aplicacoesAreas', 'aplicacoesServicos'));
    }

    public function getDadosAplicacoes($aplicacao)
    {
        $aplicacoes = Aplicacao::where('slug', $aplicacao)->first();

        $aplicacoesAreas = AreaDeNegocio::join('aplicacoes_areas', 'aplicacoes_areas.area_id', '=', 'areas_de_negocio.id')
            ->join('aplicacoes', 'aplicacoes.id', '=', 'aplicacoes_areas.aplicacao_id')
            ->select('areas_de_negocio.id as area_id', 'areas_de_negocio.slug as area_slug', 'areas_de_negocio.titulo as area_titulo', 'aplicacoes_areas.texto_area as texto_area')
            ->where('aplicacoes.slug', $aplicacao)
            ->distinct()->orderBy('areas_de_negocio.id', 'ASC')->get();

        $aplicacoesServicos = Servico::join('aplicacoes_areas_servicos', 'aplicacoes_areas_servicos.servico_id', '=', 'servicos.id')
            ->join('aplicacoes_areas', 'aplicacoes_areas.id', '=', 'aplicacoes_areas_servicos.aplicacao_area_id')
            ->join('aplicacoes', 'aplicacoes.id', '=', 'aplicacoes_areas.aplicacao_id')
            ->join('areas_de_negocio', 'areas_de_negocio.id', '=', 'aplicacoes_areas.area_id')
            ->select('aplicacoes.id as aplicacao_id', 'aplicacoes.slug as aplicacao_slug', 'aplicacoes.titulo as aplicacao_titulo', 'areas_de_negocio.id as area_id', 'areas_de_negocio.slug as area_slug', 'areas_de_negocio.titulo as area_titulo', 'servicos.id as servico_id', 'servicos.slug as servico_slug', 'servicos.titulo as servico_titulo', 'servicos.grupo_id as grupo_id')
            ->where('aplicacoes.id', $aplicacoes->id)
            ->orderBy('servicos.titulo', 'ASC')->get();

        return response()->json(['aplicacoes' => $aplicacoes, 'aplicacoesAreas' => $aplicacoesAreas, 'aplicacoesServicos' => $aplicacoesServicos]);
    }
}

laravel/app/Http/Controllers/Painel/AplicacoesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\AplicacoesRequest;
use App\Models\Aplicacao;

class AplicacoesController extends Controller
{
    public function index()
    {
        $aplicacoes = Aplicacao::orderBy('titulo', 'ASC')->get();

        return view('painel.aplicacoes.index', compact('aplicacoes'));
    }

    public function create()
    {
        return view('painel.aplicacoes.create');
    }

    public function store(AplicacoesRequest $request)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            if (isset($input['imagem'])) $input['imagem'] = Aplicacao::upload_imagem();

            Aplicacao::create($input);

            return redirect()->route('painel.aplicacoes.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Aplicacao $aplicacao)
    {
        return view('painel.aplicacoes.edit', compact('aplicacao'));
    }

    public function update(AplicacoesRequest $request, Aplicacao $aplicacao)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            if (isset($input['imagem'])) $input['imagem'] = Aplicacao::upload_imagem();

            $aplicacao->update($input);

            return redirect()->route('painel.aplicacoes.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Aplicacao $aplicacao)
    {
        try {
            $aplicacao->delete();

            return redirect()->route('painel.aplicacoes.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/aplicacoes/areas/create.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Aplicação: {{ $aplicacao->titulo }} | Áreas de Negócio |</small> Adicionar Área</h2>
</legend>

{!! Form::model($aplicacao, [
'route' => ['painel.aplicacoes.areas.store', $aplicacao->id],
'method' => 'post',
'files' => true])
!!}

@include('painel.aplicacoes.areas.form', ['submitText' => 'Inserir'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/aplicacoes/areas/edit.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Aplicação: {{ $aplicacao->titulo }} | Áreas de Negócio |</small> Editar Área</h2>
</legend>

{!! Form::model($aplicacaoArea, [
'route' => ['painel.aplicacoes.areas.update', $aplicacao->id, $aplicacaoArea->id],
'method' => 'patch',
'files' => true])
!!}

@include('painel.aplicacoes.areas.form', ['submitText' => 'Alterar'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/aplicacoes/areas/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('area_id', 'Áreas de Negócio') !!}
    {!! Form::select('area_id', $areas , old('area_id'), ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto_area', 'Texto sobre a área de negócio nesta aplicação') !!}
    {!! Form::textarea('texto_area', null, ['class' => 'form-control ckeditor', 'data-editor' => 'textEdit']) !!}
</div>

<hr>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.aplicacoes.areas.index', $aplicacao->id) }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/aplicacoes/areas/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<a href="{{ route('painel.aplicacoes.index') }}" title="Voltar para Aplicações" class="btn btn-sm btn-default">&larr; Voltar para Aplicações</a>

<legend>
    <h2>
        Aplicação: {{ $aplicacao->titulo }} | Áreas de Negócio
        <a href="{{ route('painel.aplicacoes.areas.create', $aplicacao->id) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Área</a>
    </h2>
</legend>

@if(!count($areas))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="aplicacoes_areas">
    <thead>
        <tr>
            <th>Área de Negocio</th>
            <th>Gerenciar</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($areas as $area)
        <tr class="tr-row" id="{{ $area->id }}">
            <td>{{ $area->area_titulo }}</td>
            <td><a href="{{ route('painel.aplicacoes.areas.servicos.index', [$aplicacao->id, $area->id]) }}" class="btn btn-info btn-sm">
                    <span class="glyphicon glyphicon-picture" style="margin-right:10px;"></span>Serviços
                </a></td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.aplicacoes.areas.destroy', $aplicacao->id, $area->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.aplicacoes.areas.edit', [$aplicacao->id, $area->id] ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@endsection