laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('resultados-filtro/{area}/{aplicacao}/{servico}', 'FiltroController@index')->name('filtro');
    Route::get('filtro/{area}/{aplicacao}/{servico}', 'FiltroController@filtroGeral')->name('filtroGeral');
    Route::get('empresa/{submenu}', 'EmpresaController@index')->name('empresa');
    Route::get('empresa/list/{submenu}', 'EmpresaController@getDadosEmpresa')->name('getDadosEmpresa');
    Route::get('areas-de-negocio/{area}', 'AreasDeNegocioController@index')->name('areas-de-negocio');
    Route::get('areas-de-negocio/list/{area}', 'AreasDeNegocioController@getDadosAreasDeNegocio')->name('getDadosAreasDeNegocio');
    Route::get('aplicacoes/{aplicacao}', 'AplicacoesController@index')->name('aplicacoes');
    Route::get('aplicacoes/list/{aplicacao}', 'AplicacoesController@getDadosAplicacoes')->name('getDadosAplicacoes');
    Route::get('servicos', 'ServicosController@index')->name('servicos');
    Route::get('servicos/{servico}', 'ServicosController@show')->name('servicos.show');
    Route::get('servicos/grupo/{grupo}', 'ServicosController@showServicosGrupo')->name('showServicosGrupo');
    Route::get('servicos/list/{servico}', 'ServicosController@getDadosServicos')->name('getDadosServicos');
    Route::get('galeria-de-imagens', 'GaleriaDeImagensController@index')->name('galeria-de-imagens.index');
    Route::get('galeria-de-imagens/{obra}', 'GaleriaDeImagensController@show')->name('galeria-de-imagens.show');
    Route::get('galeria-de-imagens/filtro/{area}/{aplicacao}/{servico}', 'GaleriaDeImagensController@filtroGaleria')->name('filtroGaleria');
    Route::get('artigos-tecnicos', 'ArtigosTecnicosController@index')->name('artigos-tecnicos');
    Route::get('artigos-tecnicos/{artigo}', 'ArtigosTecnicosController@openPdf')->name('artigos-tecnicos.pdf');
    Route::get('clientes', 'ClientesController@index')->name('clientes');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('busca', 'BuscaController@post')->name('busca');
    Route::get('termos-de-uso', 'TermosDeUsoController@index')->name('termos-de-uso');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
        Route::resource('capas-menus', 'CapasMenusController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('banners-header', 'BannersHeaderController');
        Route::resource('slides-home', 'SlidesHomeController');
        Route::resource('obras-destaque', 'ObrasDestaqueController', ['only' => ['index', 'create', 'store', 'destroy']]);
        Route::resource('empresa-historia', 'EmpresaHistoriaController', ['only' => ['index', 'update']]);
        Route::resource('empresa-nossa-otica', 'EmpresaNossaOticaController', ['only' => ['index', 'update']]);
        Route::resource('empresa-corpo-tecnico', 'EmpresaCorpoTecnicoController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('empresa-corpo-tecnico.equipe', 'EmpresaCorpoTecnicoEquipeController');
        Route::resource('areas-de-negocio', 'AreasDeNegocioController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('servicos-pagina', 'ServicosPaginaController', ['only' => ['index', 'update']]);
        Route::resource('servicos-grupos', 'ServicosGruposController');
        Route::resource('servicos', 'ServicosController', ['except' => 'show']);
        Route::get('servicos/{servico}/imagens/clear', [
            'as'   => 'painel.servicos.imagens.clear',
            'uses' => 'ServicosImagensController@clear'
        ]);
        Route::resource('servicos.imagens', 'ServicosImagensController', ['parameters' => ['imagens' => 'servicos_imagens']]);
        Route::resource('aplicacoes', 'AplicacoesController');
        Route::resource('aplicacoes.areas', 'AplicacoesAreasController');
        Route::resource('aplicacoes.areas.servicos', 'AplicacoesAreasServicosController', ['only' => ['index', 'create', 'store', 'destroy']]);
        Route::resource('galeria-de-imagens', 'ObrasController');
        Route::resource('galeria-de-imagens.areas', 'ObrasAreasController', ['only' => ['index', 'create', 'store', 'destroy']]);
        Route::resource('galeria-de-imagens.servicos', 'ObrasServicosController', ['only' => ['index', 'create', 'store']]);
        Route::delete('galeria-de-imagens/{obra}/servicos/{servico}', 'ObrasServicosController@destroy')->name('galeria.servicos.destroy');
        Route::resource('galeria-de-imagens.imagens', 'ObrasImagensController');
        Route::resource('artigos-tecnicos', 'ArtigosTecnicosController');
        Route::resource('clientes', 'ClientesController');
        Route::get('contato/recebidos/{recebidos}/pdf', 'ContatosRecebidosController@openPdf')->name('painel.contato.arquivos.pdf');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');
        Route::resource('termos-de-uso', 'TermosDeUsoController', ['only' => ['index', 'update']]);
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');

        // Limpar caches
        Route::get('clear-cache', function () {
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('config:cache');

            return 'DONE';
        });
    });

    // Auth - PAINEL
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Models/Home.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Home extends Model
{
    protected $table = 'home';

    protected $guarded = ['id'];

    public function scopeBusca($query, $termo)
    {
        return $query->where('titulo', 'LIKE', '%' . $termo . '%')
            ->orWhere('texto', 'LIKE', '%' . $termo . '%');
    }
}

laravel/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Models\AceiteDeCookies;
use App\Models\AreaDeNegocio;
use App\Models\BannerHeader;
use App\Models\Home;
use App\Models\ObraDestaque;
use App\Models\SlideHome;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    public function index(Request $request)
    {
        $banners = BannerHeader::ordenados()->get();

        $areas = AreaDeNegocio::orderBy('id', 'ASC')->get();

        $slides = SlideHome::ordenados()->get();

        $texto = Home::first();

        $destaques = ObraDestaque::join('obras', 'obras.id', '=', 'obras_destaque.obra_id')
            ->select('obras_destaque.id as id', 'obras_destaque.ordem as ordem', 'obras.id as obra_id', 'obras.titulo as obra_titulo', 'obras.slug as obra_slug', 'obras.capa as obra_capa')
            ->ordenados()->get();

        $verificacao = AceiteDeCookies::where('ip', $request->ip())->first();

        return view('frontend.home', compact('banners', 'areas', 'slides', 'texto', 'destaques', 'verificacao'));
    }

    public function postCookies(Request $request)
    {
        $input = $request->all();
        $input['ip'] = $request->ip();

        AceiteDeCookies::create($input);

        return redirect('/');
    }
}

laravel/app/Http/Controllers/Painel/HomeController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\HomeRequest;
use App\Models\Home;

class HomeController extends Controller
{
    public function index()
    {
        $registro = Home::first();

        return view('painel.home.pagina.edit', compact('registro'));
    }

    public function update(HomeRequest $request, Home $registro)
    {
        try {
            $input = $request->all();

            $registro->update($input);

            return redirect()->route('painel.home.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);

        }
    }
}

laravel/resources/views/painel/home/slides/create.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Home | Slides |</small> Adicionar Slide</h2>
</legend>

{!! Form::open(['route' => 'painel.slides-home.store', 'files' => true]) !!}

@include('painel.home.slides.form', ['submitText' => 'Inserir'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/home/slides/edit.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Home | Slides |</small> Editar Slide</h2>
</legend>

{!! Form::model($slide, [
'route' => ['painel.slides-home.update', $slide->id],
'method' => 'patch',
'files' => true])
!!}

@include('painel.home.slides.form', ['submitText' => 'Alterar'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/home/slides/form.blade.php
@include('painel.common.flash')

<div class="well form-group">
    {!! Form::label('imagem', 'Imagem') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/slides-home/'.$slide->imagem) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('imagem', ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('frase', 'Frase') !!}
    {!! Form::text('frase', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('link', 'Link') !!}
    {!! Form::text('link', null, ['class' => 'form-control']) !!}
</div>

<hr>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.slides-home.index') }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/home/slides/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<legend>
    <h2>
        Home | Slides
        <a href="{{ route('painel.slides-home.create') }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Slide</a>
    </h2>
</legend>

@if(!count($slides))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="slides_home">
    <thead>
        <tr>
            <th>Ordenar</th>
            <th>Imagem</th>
            <th>Frase</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($slides as $slide)
        <tr class="tr-row" id="{{ $slide->id }}">
            <td>
                <a href="#" class="btn btn-info btn-sm btn-move">
                    <span class="glyphicon glyphicon-move"></span>
                </a>
            </td>
            <td><img src="{{ asset('assets/img/slides-home/'.$slide->imagem) }}" style="width: 100%; max-width:150px;" alt=""></td>
            <td>{{ $slide->frase }}</td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.slides-home.destroy', $slide->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.slides-home.edit', $slide->id ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@endsection