laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('resultados-filtro/{area}/{aplicacao}/{servico}', 'FiltroController@index')->name('filtro');
    Route::get('filtro/{area}/{aplicacao}/{servico}', 'FiltroController@filtroGeral')->name('filtroGeral');
    Route::get('empresa/{submenu}', 'EmpresaController@index')->name('empresa');
    Route::get('empresa/list/{submenu}', 'EmpresaController@getDadosEmpresa')->name('getDadosEmpresa');
    Route::get('areas-de-negocio/{area}', 'AreasDeNegocioController@index')->name('areas-de-negocio');
    Route::get('areas-de-negocio/list/{area}', 'AreasDeNegocioController@getDadosAreasDeNegocio')->name('getDadosAreasDeNegocio');
    Route::get('aplicacoes/{aplicacao}', 'AplicacoesController@index')->name('aplicacoes');
    Route::get('aplicacoes/list/{aplicacao}', 'AplicacoesController@getDadosAplicacoes')->name('getDadosAplicacoes');
    Route::get('servicos', 'ServicosController@index')->name('servicos');
    Route::get('servicos/{servico}', 'ServicosController@show')->name('servicos.show');
    Route::get('servicos/grupo/{grupo}', 'ServicosController@showServicosGrupo')->name('showServicosGrupo');
    Route::get('servicos/list/{servico}', 'ServicosController@getDadosServicos')->name('getDadosServicos');
    Route::get('galeria-de-imagens', 'GaleriaDeImagensController@index')->name('galeria-de-imagens.index');
    Route::get('galeria-de-imagens/{obra}', 'GaleriaDeImagensController@show')->name('galeria-de-imagens.show');
    Route::get('galeria-de-imagens/filtro/{area}/{aplicacao}/{servico}', 'GaleriaDeImagensController@filtroGaleria')->name('filtroGaleria');
    Route::get('artigos-tecnicos', 'ArtigosTecnicosController@index')->name('artigos-tecnicos');
    Route::get('artigos-tecnicos/{artigo}', 'ArtigosTecnicosController@openPdf')->name('artigos-tecnicos.pdf');
    Route::get('clientes', 'ClientesController@index')->name('clientes');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('busca', 'BuscaController@post')->name('busca');
    Route::get('termos-de-uso', 'TermosDeUsoController@index')->name('termos-de-uso');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
        Route::resource('capas-menus', 'CapasMenusController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('banners-header', 'BannersHeaderController');
        Route::resource('slides-home', 'SlidesHomeController');
        Route::resource('obras-destaque', 'ObrasDestaqueController', ['only' => ['index', 'create', 'store', 'destroy']]);
        Route::resource('empresa-historia', 'EmpresaHistoriaController', ['only' => ['index', 'update']]);
        Route::resource('empresa-nossa-otica', 'EmpresaNossaOticaController', ['only' => ['index', 'update']]);
        Route::resource('empresa-corpo-tecnico', 'EmpresaCorpoTecnicoController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('empresa-corpo-tecnico.equipe', 'EmpresaCorpoTecnicoEquipeController');
        Route::resource('areas-de-negocio', 'AreasDeNegocioController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('servicos-pagina', 'ServicosPaginaController', ['only' => ['index', 'update']]);
        Route::resource('servicos-grupos', 'ServicosGruposController');
        Route::resource('servicos', 'ServicosController', ['except' => 'show']);
        Route::get('servicos/{servico}/imagens/clear', [
            'as'   => 'painel.servicos.imagens.clear',
            'uses' => 'ServicosImagensController@clear'
        ]);
        Route::resource('servicos.imagens', 'ServicosImagensController', ['parameters' => ['imagens' => 'servicos_imagens']]);
        Route::resource('aplicacoes', 'AplicacoesController');
        Route::resource('aplicacoes.areas', 'AplicacoesAreasController');
        Route::resource('aplicacoes.areas.servicos', 'AplicacoesAreasServicosController', ['only' => ['index', 'create', 'store', 'destroy']]);
        Route::resource('galeria-de-imagens', 'ObrasController');
        Route::resource('galeria-de-imagens.areas', 'ObrasAreasController', ['only' => ['index', 'create', 'store', 'destroy']]);
        Route::resource('galeria-de-imagens.servicos', 'ObrasServicosController', ['only' => ['index', 'create', 'store']]);
        Route::delete('galeria-de-imagens/{obra}/servicos/{servico}', 'ObrasServicosController@destroy')->name('galeria.servicos.destroy');
        Route::resource('galeria-de-imagens.imagens', 'ObrasImagensController');
        Route::resource('artigos-tecnicos', 'ArtigosTecnicosController');
        Route::resource('clientes', 'ClientesController');
        Route::get('contato/recebidos/{recebidos}/pdf', 'ContatosRecebidosController@openPdf')->name('painel.contato.arquivos.pdf');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');
        Route::resource('termos-de-uso', 'TermosDeUsoController', ['only' => ['index', 'update']]);
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');

        // Limpar caches
        Route::get('clear-cache', function () {
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('config:cache');

            return 'DONE';
        });
    });

    // Auth - PAINEL
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/resources/views/painel/empresa/corpo-tecnico/equipe/create.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Empresa | Corpo Técnico | Equipe |</small> Adicionar Membro</h2>
</legend>

{!! Form::model($registro, [
'route' => ['painel.empresa-corpo-tecnico.equipe.store', $registro->id],
'method' => 'post',
'files' => true])
!!}

@include('painel.empresa.corpo-tecnico.equipe.form', ['submitText' => 'Inserir'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/empresa/corpo-tecnico/equipe/edit.blade.php
@extends('painel.common.template')

@section('content')

<legend>
    <h2><small>Empresa | Corpo Técnico | Equipe |</small> Editar Membro</h2>
</legend>

{!! Form::model($equipe, [
'route' => ['painel.empresa-corpo-tecnico.equipe.update', $registro->id, $equipe->id],
'method' => 'patch',
'files' => true])
!!}

@include('painel.empresa.corpo-tecnico.equipe.form', ['submitText' => 'Alterar'])

{!! Form::close() !!}

@endsection

laravel/resources/views/painel/empresa/corpo-tecnico/equipe/form.blade.php
@include('painel.common.flash')

<div class="form-group">
    {!! Form::label('nome', 'Nome') !!}
    {!! Form::text('nome', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('texto_sobre', 'Texto Sobre') !!}
    {!! Form::textarea('texto_sobre', null, ['class' => 'form-control ckeditor', 'data-editor' => 'clean']) !!}
</div>

<div class="well form-group">
    {!! Form::label('foto', 'Foto') !!}
    @if($submitText == 'Alterar')
    <img src="{{ url('assets/img/corpo-tecnico-equipe/'.$equipe->foto) }}" style="display:block; margin-bottom: 10px; max-width: 100%;">
    @endif
    {!! Form::file('foto', ['class' => 'form-control']) !!}
</div>

<hr>

{!! Form::submit($submitText, ['class' => 'btn btn-success']) !!}

<a href="{{ route('painel.empresa-corpo-tecnico.equipe.index', $registro->id) }}" class="btn btn-default btn-voltar">Voltar</a>

laravel/resources/views/painel/empresa/corpo-tecnico/equipe/index.blade.php
@extends('painel.common.template')

@section('content')

@include('painel.common.flash')

<a href="{{ route('painel.empresa-corpo-tecnico.index') }}" title="Voltar para Corpo Técnico" class="btn btn-sm btn-default">&larr; Voltar para Corpo Técnico</a>

<legend>
    <h2>
        Empresa | Corpo Técnico | Equipe
        <a href="{{ route('painel.empresa-corpo-tecnico.equipe.create', $registro->id) }}" class="btn btn-success btn-sm pull-right"><span class="glyphicon glyphicon-plus" style="margin-right:10px;"></span>Adicionar Membro</a>
    </h2>
</legend>

@if(!count($equipe))
<div class="alert alert-warning" role="alert">Nenhum registro encontrado.</div>
@else
<table class="table table-striped table-bordered table-hover table-info table-sortable" data-table="empresa_corpo_tecnico_equipe">
    <thead>
        <tr>
            <th>Ordem</th>
            <th>Foto</th>
            <th>Nome</th>
            <th>Sobre</th>
            <th class="no-filter"><span class="glyphicon glyphicon-cog"></span></th>
        </tr>
    </thead>

    <tbody>
        @foreach ($equipe as $membro)
        <tr class="tr-row" id="{{ $membro->id }}">
            <td>
                <a href="#" class="btn btn-info btn-sm btn-move">
                    <span class="glyphicon glyphicon-move"></span>
                </a>
            </td>
            <td><img src="{{ asset('assets/img/corpo-tecnico-equipe/'.$membro->foto) }}" style="width: 100%; max-width:100px;" alt=""></td>
            <td>{{ $membro->nome }}</td>
            <td>{!! $membro->texto_sobre !!}</td>
            <td class="crud-actions">
                {!! Form::open([
                'route' => ['painel.empresa-corpo-tecnico.equipe.destroy', $registro->id, $membro->id],
                'method' => 'delete'
                ]) !!}

                <div class="btn-group btn-group-sm">
                    <a href="{{ route('painel.empresa-corpo-tecnico.equipe.edit', [$registro->id, $membro->id] ) }}" class="btn btn-primary btn-sm pull-left">
                        <span class="glyphicon glyphicon-pencil" style="margin-right:10px;"></span>Editar
                    </a>

                    <button type="submit" class="btn btn-danger btn-sm btn-delete"><span class="glyphicon glyphicon-remove" style="margin-right:10px;"></span>Excluir</button>
                </div>

                {!! Form::close() !!}
            </td>
        </tr>
        @endforeach
    </tbody>
</table>
@endif

@endsection