laravel/app/Http/routes.php
<?php

use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;

Route::group(['middleware' => ['web']], function () {
    Route::get('/', 'HomeController@index')->name('home');
    Route::get('resultados-filtro/{area}/{aplicacao}/{servico}', 'FiltroController@index')->name('filtro');
    Route::get('filtro/{area}/{aplicacao}/{servico}', 'FiltroController@filtroGeral')->name('filtroGeral');
    Route::get('empresa/{submenu}', 'EmpresaController@index')->name('empresa');
    Route::get('empresa/list/{submenu}', 'EmpresaController@getDadosEmpresa')->name('getDadosEmpresa');
    Route::get('areas-de-negocio/{area}', 'AreasDeNegocioController@index')->name('areas-de-negocio');
    Route::get('areas-de-negocio/list/{area}', 'AreasDeNegocioController@getDadosAreasDeNegocio')->name('getDadosAreasDeNegocio');
    Route::get('aplicacoes/{aplicacao}', 'AplicacoesController@index')->name('aplicacoes');
    Route::get('aplicacoes/list/{aplicacao}', 'AplicacoesController@getDadosAplicacoes')->name('getDadosAplicacoes');
    Route::get('servicos', 'ServicosController@index')->name('servicos');
    Route::get('servicos/{servico}', 'ServicosController@show')->name('servicos.show');
    Route::get('servicos/grupo/{grupo}', 'ServicosController@showServicosGrupo')->name('showServicosGrupo');
    Route::get('servicos/list/{servico}', 'ServicosController@getDadosServicos')->name('getDadosServicos');
    Route::get('galeria-de-imagens', 'GaleriaDeImagensController@index')->name('galeria-de-imagens.index');
    Route::get('galeria-de-imagens/{obra}', 'GaleriaDeImagensController@show')->name('galeria-de-imagens.show');
    Route::get('galeria-de-imagens/filtro/{area}/{aplicacao}/{servico}', 'GaleriaDeImagensController@filtroGaleria')->name('filtroGaleria');
    Route::get('artigos-tecnicos', 'ArtigosTecnicosController@index')->name('artigos-tecnicos');
    Route::get('artigos-tecnicos/{artigo}', 'ArtigosTecnicosController@openPdf')->name('artigos-tecnicos.pdf');
    Route::get('clientes', 'ClientesController@index')->name('clientes');
    Route::get('contato', 'ContatoController@index')->name('contato');
    Route::post('contato', 'ContatoController@post')->name('contato.post');
    Route::post('busca', 'BuscaController@post')->name('busca');
    Route::get('termos-de-uso', 'TermosDeUsoController@index')->name('termos-de-uso');
    Route::get('politica-de-privacidade', 'PoliticaDePrivacidadeController@index')->name('politica-de-privacidade');
    Route::post('aceite-de-cookies', 'HomeController@postCookies')->name('aceite-de-cookies.post');

    // Painel
    Route::group([
        'prefix'     => 'painel',
        'namespace'  => 'Painel',
        'middleware' => ['auth']
    ], function () {
        Route::get('/', 'PainelController@index')->name('painel');
        Route::post('ckeditor-upload', 'PainelController@imageUpload');
        Route::post('order', 'PainelController@order');
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::resource('home', 'HomeController', ['only' => ['index', 'update']]);
        Route::resource('capas-menus', 'CapasMenusController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('banners-header', 'BannersHeaderController');
        Route::resource('slides-home', 'SlidesHomeController');
        Route::resource('obras-destaque', 'ObrasDestaqueController', ['only' => ['index', 'create', 'store', 'destroy']]);
        Route::resource('empresa-historia', 'EmpresaHistoriaController', ['only' => ['index', 'update']]);
        Route::resource('empresa-nossa-otica', 'EmpresaNossaOticaController', ['only' => ['index', 'update']]);
        Route::resource('empresa-corpo-tecnico', 'EmpresaCorpoTecnicoController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('empresa-corpo-tecnico.equipe', 'EmpresaCorpoTecnicoEquipeController');
        Route::resource('areas-de-negocio', 'AreasDeNegocioController', ['only' => ['index', 'edit', 'update']]);
        Route::resource('servicos-pagina', 'ServicosPaginaController', ['only' => ['index', 'update']]);
        Route::resource('servicos-grupos', 'ServicosGruposController');
        Route::resource('servicos', 'ServicosController', ['except' => 'show']);
        Route::get('servicos/{servico}/imagens/clear', [
            'as'   => 'painel.servicos.imagens.clear',
            'uses' => 'ServicosImagensController@clear'
        ]);
        Route::resource('servicos.imagens', 'ServicosImagensController', ['parameters' => ['imagens' => 'servicos_imagens']]);
        Route::resource('aplicacoes', 'AplicacoesController');
        Route::resource('aplicacoes.areas', 'AplicacoesAreasController');
        Route::resource('aplicacoes.areas.servicos', 'AplicacoesAreasServicosController', ['only' => ['index', 'create', 'store', 'destroy']]);
        Route::resource('galeria-de-imagens', 'ObrasController');
        Route::resource('galeria-de-imagens.areas', 'ObrasAreasController', ['only' => ['index', 'create', 'store', 'destroy']]);
        Route::resource('galeria-de-imagens.servicos', 'ObrasServicosController', ['only' => ['index', 'create', 'store']]);
        Route::delete('galeria-de-imagens/{obra}/servicos/{servico}', 'ObrasServicosController@destroy')->name('galeria.servicos.destroy');
        Route::resource('galeria-de-imagens.imagens', 'ObrasImagensController');
        Route::resource('artigos-tecnicos', 'ArtigosTecnicosController');
        Route::resource('clientes', 'ClientesController');
        Route::get('contato/recebidos/{recebidos}/pdf', 'ContatosRecebidosController@openPdf')->name('painel.contato.arquivos.pdf');
        Route::get('contato/recebidos/{recebidos}/toggle', ['as' => 'painel.contato.recebidos.toggle', 'uses' => 'ContatosRecebidosController@toggle']);
        Route::resource('contato/recebidos', 'ContatosRecebidosController');
        Route::resource('contato', 'ContatoController');
        Route::resource('configuracoes', 'ConfiguracoesController', ['only' => ['index', 'update']]);
        Route::resource('usuarios', 'UsuariosController');
        Route::resource('termos-de-uso', 'TermosDeUsoController', ['only' => ['index', 'update']]);
        Route::resource('politica-de-privacidade', 'PoliticaDePrivacidadeController', ['only' => ['index', 'update']]);
        Route::get('aceite-de-cookies', 'AceiteDeCookiesController@index')->name('painel.aceite-de-cookies');

        // Limpar caches
        Route::get('clear-cache', function () {
            $exitCode = Artisan::call('config:clear');
            $exitCode = Artisan::call('cache:clear');
            $exitCode = Artisan::call('route:clear');
            $exitCode = Artisan::call('view:clear');
            $exitCode = Artisan::call('config:cache');

            return 'DONE';
        });
    });

    // Auth - PAINEL
    Route::group([
        'prefix'    => 'painel',
        'namespace' => 'Auth'
    ], function () {
        Route::get('login', 'AuthController@showLoginForm')->name('auth');
        Route::post('login', 'AuthController@login')->name('login');
        Route::get('logout', 'AuthController@logout')->name('logout');
        Route::get('esqueci-minha-senha', 'PasswordController@sendEmail')->name('esqueci-minha-senha');
        Route::post('esqueci-minha-senha', 'PasswordController@sendResetLinkEmail')->name('esqueci-minha-senha.post');
        Route::get('reset/{token}', 'PasswordController@showResetForm')->name('password-reset');
        Route::post('reset', 'PasswordController@reset')->name('password-reset.post');
    });
});

laravel/app/Http/Controllers/Painel/AceiteDeCookiesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Models\AceiteDeCookies;

class AceiteDeCookiesController extends Controller
{
    public function index()
    {
        $registros = AceiteDeCookies::orderBy('created_at', 'DESC')->get();

        return view('painel.cookies.index', compact('registros'));
    }
}

laravel/app/Http/Controllers/Painel/AplicacoesAreasController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\AplicacoesAreasRequest;
use App\Models\Aplicacao;
use App\Models\AplicacaoArea;
use App\Models\AreaDeNegocio;

class AplicacoesAreasController extends Controller
{
    public function index(Aplicacao $aplicacao)
    {
        $areas = AplicacaoArea::aplicacao($aplicacao->id)
            ->join('areas_de_negocio', 'areas_de_negocio.id', '=', 'aplicacoes_areas.area_id')
            ->join('aplicacoes', 'aplicacoes.id', '=', 'aplicacoes_areas.aplicacao_id')
            ->select('areas_de_negocio.id as area_id', 'areas_de_negocio.titulo as area_titulo', 'aplicacoes.id as aplicacao_id', 'aplicacoes.titulo as aplicacao_titulo', 'aplicacoes_areas.id as id')
            ->orderBy('areas_de_negocio.id', 'ASC')
            ->get();

        return view('painel.aplicacoes.areas.index', compact('areas', 'aplicacao'));
    }

    public function create(Aplicacao $aplicacao)
    {
        $areas = AreaDeNegocio::orderBy('id', 'ASC')->pluck('titulo', 'id');

        return view('painel.aplicacoes.areas.create', compact('aplicacao', 'areas'));
    }

    public function store(AplicacoesAreasRequest $request, Aplicacao $aplicacao)
    {
        try {
            $input = $request->all();
            $input['aplicacao_id'] = $aplicacao->id;

            $count = count(AplicacaoArea::where('aplicacao_id', $aplicacao->id)->where('area_id', $input['area_id'])->get());
            
            if ($count == 0) {
                AplicacaoArea::create($input);
            } else {
                return back()->withErrors(['Erro ao adicionar registro: Verifique se essa área de negócio ja está cadastrada']);
            }

            return redirect()->route('painel.aplicacoes.areas.index', $aplicacao->id)->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Aplicacao $aplicacao, $aplicacaoArea)
    {
        $areas = AreaDeNegocio::orderBy('id', 'ASC')->pluck('titulo', 'id');

        $aplicacaoArea = AplicacaoArea::find($aplicacaoArea);

        return view('painel.aplicacoes.areas.edit', compact('aplicacao', 'areas', 'aplicacaoArea'));
    }

    public function update(AplicacoesAreasRequest $request, Aplicacao $aplicacao, $aplicacaoArea)
    {
        try {
            $input = $request->all();
            $input['aplicacao_id'] = $aplicacao->id;

            $aplicacaoArea = AplicacaoArea::find($aplicacaoArea);

            $aplicacaoArea->update($input);

            return redirect()->route('painel.aplicacoes.areas.index', $aplicacao->id)->with('success', 'Registro alterado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Aplicacao $registro, $aplicacaoArea)
    {
        try {
            $aplicacaoArea = AplicacaoArea::find($aplicacaoArea);

            $aplicacaoArea->delete();

            return redirect()->route('painel.aplicacoes.areas.index', $registro->id)->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/AplicacoesAreasServicosController.php
<?php

namespace App\Http\Controllers\Painel;

use Illuminate\Http\Request;

use App\Http\Controllers\Controller;
use App\Models\Aplicacao;
use App\Models\AplicacaoArea;
use App\Models\AplicacaoAreaServico;
use App\Models\AreaDeNegocio;
use App\Models\Servico;

class AplicacoesAreasServicosController extends Controller
{
    public function index(Aplicacao $aplicacao, $area)
    {
        $aplicacaoArea = AplicacaoArea::find($area);
        
        $servicos = AplicacaoAreaServico::where('aplicacao_area_id', $aplicacaoArea->id)
            ->join('servicos', 'servicos.id', '=', 'aplicacoes_areas_servicos.servico_id')
            ->select('servicos.id as servico_id', 'servicos.titulo as servico_titulo', 'aplicacoes_areas_servicos.id as id')
            ->orderBy('servico_titulo', 'ASC')
            ->get();

        $areaDeNegocio = AreaDeNegocio::find($aplicacaoArea->area_id);

        return view('painel.aplicacoes.areas.servicos.index', compact('area', 'aplicacao', 'servicos', 'areaDeNegocio'));
    }

    public function create(Aplicacao $aplicacao, $area)
    {
        $aplicacaoArea = AplicacaoArea::find($area);

        $servicos = Servico::orderBy('titulo', 'ASC')->pluck('titulo', 'id');

        $areaDeNegocio = AreaDeNegocio::find($aplicacaoArea->area_id);

        return view('painel.aplicacoes.areas.servicos.create', compact('aplicacao', 'area', 'servicos', 'areaDeNegocio'));
    }

    public function store(Request $request, Aplicacao $aplicacao, $area)
    {
        try {
            $input = $request->all();
            $input['aplicacao_area_id'] = $area;

            $count = count(AplicacaoAreaServico::where('aplicacao_area_id', $input['aplicacao_area_id'])->where('servico_id', $input['servico_id'])->get());
            
            if ($count == 0) {
                AplicacaoAreaServico::create($input);
            } else {
                return back()->withErrors(['Erro ao adicionar registro: Verifique se esse serviço ja está cadastrado']);
            }

            return redirect()->route('painel.aplicacoes.areas.servicos.index', [$aplicacao->id, $area])->with('success', 'Registro adicionado com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Aplicacao $aplicacao, $area_id, $servico_id)
    {
        try {
            $area = AplicacaoArea::where('id', $area_id)->where('aplicacao_id', $aplicacao->id)->first();
            $servico = AplicacaoAreaServico::where('servico_id', $servico_id->id)->where('aplicacao_area_id', $area->id)->first();

            $servico->delete();

            return redirect()->route('painel.aplicacoes.areas.servicos.index', [$aplicacao->id, $area->id])->with('success', 'Registro excluído com sucesso.');
        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/AplicacoesController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\AplicacoesRequest;
use App\Models\Aplicacao;

class AplicacoesController extends Controller
{
    public function index()
    {
        $aplicacoes = Aplicacao::orderBy('titulo', 'ASC')->get();

        return view('painel.aplicacoes.index', compact('aplicacoes'));
    }

    public function create()
    {
        return view('painel.aplicacoes.create');
    }

    public function store(AplicacoesRequest $request)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            if (isset($input['imagem'])) $input['imagem'] = Aplicacao::upload_imagem();

            Aplicacao::create($input);

            return redirect()->route('painel.aplicacoes.index')->with('success', 'Registro adicionado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao adicionar registro: ' . $e->getMessage()]);
        }
    }

    public function edit(Aplicacao $aplicacao)
    {
        return view('painel.aplicacoes.edit', compact('aplicacao'));
    }

    public function update(AplicacoesRequest $request, Aplicacao $aplicacao)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($request->titulo, '-');

            if (isset($input['imagem'])) $input['imagem'] = Aplicacao::upload_imagem();

            $aplicacao->update($input);

            return redirect()->route('painel.aplicacoes.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }

    public function destroy(Aplicacao $aplicacao)
    {
        try {
            $aplicacao->delete();

            return redirect()->route('painel.aplicacoes.index')->with('success', 'Registro excluído com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao excluir registro: ' . $e->getMessage()]);
        }
    }
}

laravel/app/Http/Controllers/Painel/AreasDeNegocioController.php
<?php

namespace App\Http\Controllers\Painel;

use App\Http\Controllers\Controller;
use App\Http\Requests\AreasDeNegocioRequest;
use App\Models\AreaDeNegocio;

class AreasDeNegocioController extends Controller
{
    public function index()
    {
        $areas = AreaDeNegocio::orderBy('id', 'ASC')->get();

        return view('painel.areas-de-negocio.index', compact('areas'));
    }

    public function edit(AreaDeNegocio $area)
    {
        return view('painel.areas-de-negocio.edit', compact('area'));
    }

    public function update(AreasDeNegocioRequest $request, AreaDeNegocio $area)
    {
        try {
            $input = $request->all();
            $input['slug'] = str_slug($area->titulo, '-');

            if (isset($input['imagem'])) $input['imagem'] = AreaDeNegocio::upload_imagem();

            $area->update($input);

            return redirect()->route('painel.areas-de-negocio.index')->with('success', 'Registro alterado com sucesso.');

        } catch (\Exception $e) {

            return back()->withErrors(['Erro ao alterar registro: ' . $e->getMessage()]);
        }
    }
}

laravel/resources/views/painel/common/flash.blade.php
@if(session('success'))
   <div class="alert alert-block alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {!! session('success') !!}
    </div>
@endif

@if($errors->any())
    <div class="alert alert-block alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        @foreach($errors->all() as $error)
        {!! $error !!}<br>
        @endforeach
    </div>
@endif

laravel/resources/views/painel/common/header.blade.php
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{{ url('/') }}">{{ config('app.name') }}</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            @include('painel.common.nav')

            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown @if(Tools::routeIs(['painel.usuarios*', 'painel.configuracoes*', 'painel.termos-de-uso*', 'painel.politica-de-privacidade*'])) active @endif">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <span class="glyphicon glyphicon-cog small" style="margin-right:3px"></span>
                        <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                        <li @if(Tools::routeIs('painel.termos-de-uso*')) class="active" @endif>
                            <a href="{{ route('painel.termos-de-uso.index') }}">Termos de Uso</a>
                        </li>
                        <li @if(Tools::routeIs('painel.politica-de-privacidade*')) class="active" @endif>
                            <a href="{{ route('painel.politica-de-privacidade.index') }}">Politica de Privacidade</a>
                        </li>
                        <li @if(Tools::routeIs('painel.aceite-de-cookies*')) class="active" @endif>
                            <a href="{{ route('painel.aceite-de-cookies') }}">Relatório de Cookies</a>
                        </li>
                        <li @if(Tools::routeIs('painel.configuracoes*')) class="active" @endif>
                            <a href="{{ route('painel.configuracoes.index') }}">Configurações</a>
                        </li>
                        <li @if(Tools::routeIs('painel.usuarios*')) class="active" @endif>
                            <a href="{{ route('painel.usuarios.index') }}">Usuários</a>
                        </li>
                        <li><a href="{{ route('logout') }}">Logout</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>

laravel/resources/views/painel/common/nav.blade.php
<ul class="nav navbar-nav">

    <li class="dropdown @if(Tools::routeIs(['painel.home*', 'painel.capas-menus*', 'painel.banners-header*', 'painel.banners-home*', 'painel.obras-destaque*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Home<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.capas-menus*')) class="active" @endif>
                <a href="{{ route('painel.capas-menus.index') }}">Capas dos Menus</a>
            </li>
            <li @if(Tools::routeIs('painel.banners-header*')) class="active" @endif>
                <a href="{{ route('painel.banners-header.index') }}">Home - 1.Banners</a>
            </li>
            <li @if(Tools::routeIs('painel.slides-home*')) class="active" @endif>
                <a href="{{ route('painel.slides-home.index') }}">Home - 2.Slides</a>
            </li>
            <li @if(Tools::routeIs('painel.home*')) class="active" @endif>
                <a href="{{ route('painel.home.index') }}">Home - 3.Faixa de texto</a>
            </li>
            <li @if(Tools::routeIs('painel.obras-destaque*')) class="active" @endif>
                <a href="{{ route('painel.obras-destaque.index') }}">Home - 4.Obras em destaque</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.empresa-historia*', 'painel.empresa-nossa-otica*', 'painel.empresa-corpo-tecnico*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Empresa<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.empresa-historia*')) class="active" @endif>
                <a href="{{ route('painel.empresa-historia.index') }}">História</a>
            </li>
            <li @if(Tools::routeIs('painel.empresa-nossa-otica*')) class="active" @endif>
                <a href="{{ route('painel.empresa-nossa-otica.index') }}">Nossa Ótica</a>
            </li>
            <li @if(Tools::routeIs('painel.empresa-corpo-tecnico*')) class="active" @endif>
                <a href="{{ route('painel.empresa-corpo-tecnico.index') }}">Corpo Técnico</a>
            </li>
        </ul>
    </li>

    <li @if(Tools::routeIs('painel.areas-de-negocio*')) class="active" @endif>
        <a href="{{ route('painel.areas-de-negocio.index') }}">Áreas de Negócio</a>
    </li>

    <li @if(Tools::routeIs('painel.aplicacoes*')) class="active" @endif>
        <a href="{{ route('painel.aplicacoes.index') }}">Aplicações</a>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.servicos-pagina.*', 'painel.servicos-grupos.*', 'painel.servicos.*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Serviços<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.servicos-pagina.index')) class="active" @endif>
                <a href="{{ route('painel.servicos-pagina.index') }}">Texto da Página</a>
            </li>
            <li @if(Tools::routeIs('painel.servicos-grupos.*')) class="active" @endif>
                <a href="{{ route('painel.servicos-grupos.index') }}">Grupos de Serviços</a>
            </li>
            <li @if(Tools::routeIs('painel.servicos.*')) class="active" @endif>
                <a href="{{ route('painel.servicos.index') }}">Serviços</a>
            </li>
        </ul>
    </li>

    <li @if(Tools::routeIs('painel.galeria-de-imagens*')) class="active" @endif>
        <a href="{{ route('painel.galeria-de-imagens.index') }}">Galeria/Obras</a>
    </li>

    <li class="dropdown @if(Tools::routeIs(['painel.artigos-tecnicos*', 'painel.clientes*'])) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Artigos/Clientes<b class="caret"></b></a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.artigos-tecnicos*')) class="active" @endif>
                <a href="{{ route('painel.artigos-tecnicos.index') }}">Artigos Técnicos</a>
            </li>
            <li @if(Tools::routeIs('painel.clientes*')) class="active" @endif>
                <a href="{{ route('painel.clientes.index') }}">Clientes</a>
            </li>
        </ul>
    </li>

    <li class="dropdown @if(Tools::routeIs('painel.contato*')) active @endif">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Contato
            @if($contatosNaoLidos >= 1)
            <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
            @endif
            <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
            <li @if(Tools::routeIs('painel.contato.index')) class="active" @endif>
                <a href="{{ route('painel.contato.index') }}">Informações de Contato</a>
            </li>
            <li @if(Tools::routeIs('painel.contato.recebidos*')) class="active" @endif>
                <a href="{{ route('painel.contato.recebidos.index') }}">
                    Contatos Recebidos
                    @if($contatosNaoLidos >= 1)
                    <span class="label label-success" style="margin-left:3px;">{{ $contatosNaoLidos }}</span>
                    @endif
                </a>
            </li>
        </ul>
    </li>

</ul>

laravel/resources/views/painel/common/template.blade.php
<!doctype html>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <base href="{{ url('/') }}">

    <title>{{ config('app.name') }} - Painel Administrativo</title>

    <link rel="stylesheet" href="{{ asset('assets/vendor/bootswatch-dist/css/bootstrap.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/vendor/jquery-ui/themes/cupertino/jquery-ui.min.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/vendor.painel.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/css/painel.css') }}">
</head>
<body>
    @include('painel.common.header')

    <div class="container" style="padding-bottom:30px;">
        @yield('content')
    </div>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script src="{{ asset('assets/vendor/jquery/dist/jquery.min.js') }}"></script>
    <script src="{{ asset('assets/vendor/ckeditor/ckeditor.js') }}"></script>
    <script src="{{ asset('assets/js/vendor.painel.js') }}"></script>
    <script src="{{ asset('assets/js/painel.js') }}"></script>
</body>
</html>